"""The table shape, defined exactly once.

``COLUMNS`` is the single source of column order for every backend's INSERT and
for the DDL emitted by :func:`ddl_for`. The DDL is hand-written to match what
Django's own migration produces for
``eventlog_pro.contrib.django.models.EventLog``, so a table created by the core
backends can be adopted by ``migrate --fake-initial`` and both modes can read
each other's rows. ``tests/test_schema_parity.py`` enforces that promise.
"""

from __future__ import annotations

import hashlib
from datetime import datetime, timezone
from typing import Final

from .exceptions import ConfigurationError

__all__ = [
    "COLUMNS",
    "CHAR_COLUMNS",
    "MAX_CHARFIELD_LENGTH",
    "DEFAULT_TABLE",
    "DIALECTS",
    "INDEXES",
    "validate_table_name",
    "normalize_dialect",
    "quote_identifier",
    "placeholder",
    "ddl_for",
    "create_table_sql",
    "index_statements",
    "insert_sql",
    "to_db_datetime",
]

#: Column order, matching the declaration order of the Django model.
COLUMNS: Final[tuple[str, ...]] = (
    "created_at",
    "created_by",
    "app",
    "category",
    "sub_category",
    "event_code",
    "event_type",
    "entity_app",
    "entity_model",
    "entity_id",
    "remarks",
    "data",
)

#: The ``varchar(100)`` columns. Values are truncated to fit, never rejected.
CHAR_COLUMNS: Final[tuple[str, ...]] = (
    "created_by",
    "app",
    "category",
    "sub_category",
    "event_code",
    "event_type",
    "entity_app",
    "entity_model",
    "entity_id",
)

MAX_CHARFIELD_LENGTH: Final[int] = 100

DEFAULT_TABLE: Final[str] = "eventlog_eventlog"

DIALECTS: Final[tuple[str, ...]] = ("sqlite", "postgresql", "mysql")

_DIALECT_ALIASES: Final[dict[str, str]] = {
    "sqlite": "sqlite",
    "sqlite3": "sqlite",
    "postgres": "postgresql",
    "postgresql": "postgresql",
    "psycopg": "postgresql",
    "mysql": "mysql",
    "mariadb": "mysql",
}

#: ``(name suffix, indexed expression)`` — the three indexes the source app
#: lacks. Shipped in the Django app as ``0002_add_indexes`` so an existing
#: install can ``--fake-initial`` 0001 and really apply 0002.
INDEXES: Final[tuple[tuple[str, tuple[str, ...]], ...]] = (
    ("created", ("created_at DESC",)),
    ("app_cat", ("app", "category", "event_code")),
    ("entity", ("entity_app", "entity_model", "entity_id")),
)

#: Django refuses index names longer than this (``models.E034``), for Oracle's
#: sake. The core DDL and the model must agree, so both go through
#: :func:`index_name` and both stay inside the limit.
MAX_INDEX_NAME_LENGTH: Final[int] = 30

# Per-dialect column types. Kept verbatim-comparable to Django's schema editor
# output; see the parity test before touching anything here.
_TYPES: Final[dict[str, dict[str, str]]] = {
    "sqlite": {
        "id": "integer NOT NULL PRIMARY KEY AUTOINCREMENT",
        "created_at": "datetime NOT NULL",
        "char": f"varchar({MAX_CHARFIELD_LENGTH}) NOT NULL",
        "remarks": "text NOT NULL",
        # Django's SQLite JSONField carries this CHECK constraint.
        "data": 'text NOT NULL CHECK ((JSON_VALID("data") OR "data" IS NULL))',
    },
    "postgresql": {
        # Django >= 4.1 emits an identity column, not bigserial.
        "id": "bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "created_at": "timestamp with time zone NOT NULL",
        "char": f"varchar({MAX_CHARFIELD_LENGTH}) NOT NULL",
        "remarks": "text NOT NULL",
        "data": "jsonb NOT NULL",
    },
    "mysql": {
        "id": "bigint NOT NULL AUTO_INCREMENT PRIMARY KEY",
        "created_at": "datetime(6) NOT NULL",
        "char": f"varchar({MAX_CHARFIELD_LENGTH}) NOT NULL",
        "remarks": "longtext NOT NULL",
        "data": "json NOT NULL",
    },
}

_TABLE_NAME_ALLOWED = frozenset("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_")


def normalize_dialect(dialect: str) -> str:
    """Map a DSN scheme or dialect alias onto one of :data:`DIALECTS`."""
    try:
        return _DIALECT_ALIASES[dialect.lower()]
    except KeyError:
        raise ConfigurationError(
            f"Unknown SQL dialect {dialect!r}. Known: {', '.join(DIALECTS)}."
        ) from None


def validate_table_name(table: str) -> str:
    """Validate the one user string that reaches SQL unparameterised.

    A whitelist, not an escape function: ``^[A-Za-z_][A-Za-z0-9_]*$``, at most
    64 characters (the tightest limit among the supported databases).
    """
    if not table:
        raise ConfigurationError("Table name must not be empty.")
    if len(table) > 64:
        raise ConfigurationError(f"Table name {table!r} is longer than 64 characters.")
    if table[0].isdigit() or not set(table) <= _TABLE_NAME_ALLOWED:
        raise ConfigurationError(
            f"Invalid table name {table!r}. Table names must match ^[A-Za-z_][A-Za-z0-9_]*$."
        )
    return table


def quote_identifier(name: str, dialect: str) -> str:
    """Quote an already-validated identifier for *dialect*."""
    return f"`{name}`" if normalize_dialect(dialect) == "mysql" else f'"{name}"'


def placeholder(dialect: str, column: str = "") -> str:
    """The parameter placeholder for *column* in *dialect*."""
    d = normalize_dialect(dialect)
    if d == "sqlite":
        return "?"
    if d == "postgresql" and column == "data":
        # json.dumps on the Python side, cast in SQL — never psycopg's Jsonb.
        return "%s::jsonb"
    return "%s"


def create_table_sql(dialect: str, table: str) -> str:
    """``CREATE TABLE IF NOT EXISTS`` for *table* in *dialect*."""
    d = normalize_dialect(dialect)
    table = validate_table_name(table)
    types = _TYPES[d]
    q = quote_identifier

    defs = [f"{q('id', d)} {types['id']}"]
    for column in COLUMNS:
        if column == "created_at":
            column_type = types["created_at"]
        elif column in CHAR_COLUMNS:
            column_type = types["char"]
        elif column == "remarks":
            column_type = types["remarks"]
        else:
            column_type = types["data"]
        defs.append(f"{q(column, d)} {column_type}")

    body = ",\n    ".join(defs)
    suffix = " ENGINE=InnoDB DEFAULT CHARSET=utf8mb4" if d == "mysql" else ""
    return f"CREATE TABLE IF NOT EXISTS {q(table, d)} (\n    {body}\n){suffix}"


def index_name(table: str, suffix: str) -> str:
    """Deterministic index name, at most :data:`MAX_INDEX_NAME_LENGTH` characters.

    Readable for the default table (``eventlog_eventlog_created``); for a long
    custom table name it falls back to a short prefix plus a digest of the
    table, which stays deterministic and collision-free.
    """
    name = f"{table}_{suffix}"
    if len(name) <= MAX_INDEX_NAME_LENGTH:
        return name
    digest = hashlib.md5(name.encode("utf-8"), usedforsecurity=False).hexdigest()[:8]
    return f"el_{suffix}_{digest}"[:MAX_INDEX_NAME_LENGTH]


def index_statements(dialect: str, table: str) -> tuple[str, ...]:
    """The three ``CREATE INDEX`` statements.

    MySQL has no ``CREATE INDEX IF NOT EXISTS``; its backend swallows the
    duplicate-key-name error instead.
    """
    d = normalize_dialect(dialect)
    table = validate_table_name(table)
    q = quote_identifier
    if_not_exists = "" if d == "mysql" else "IF NOT EXISTS "

    statements = []
    for suffix, columns in INDEXES:
        cols = ", ".join(
            f"{q(c.split(' ')[0], d)} {c.split(' ', 1)[1]}" if " " in c else q(c, d)
            for c in columns
        )
        statements.append(
            f"CREATE INDEX {if_not_exists}{q(index_name(table, suffix), d)} "
            f"ON {q(table, d)} ({cols})"
        )
    return tuple(statements)


def ddl_for(dialect: str, table: str = DEFAULT_TABLE) -> tuple[str, ...]:
    """Every statement needed to materialise the event table in *dialect*."""
    return (create_table_sql(dialect, table), *index_statements(dialect, table))


def insert_sql(dialect: str, table: str = DEFAULT_TABLE) -> str:
    """``INSERT`` covering all of :data:`COLUMNS`, in order."""
    d = normalize_dialect(dialect)
    table = validate_table_name(table)
    q = quote_identifier
    columns = ", ".join(q(c, d) for c in COLUMNS)
    values = ", ".join(placeholder(d, c) for c in COLUMNS)
    sql = f"INSERT INTO {q(table, d)} ({columns}) VALUES ({values})"
    if d == "postgresql":
        sql += f" RETURNING {q('id', d)}, {q('created_at', d)}"
    return sql


def to_db_datetime(value: datetime, dialect: str) -> datetime | str:
    """Render *value* the way Django's converters expect to read it back.

    With ``USE_TZ=True`` Django stores SQLite and MySQL datetimes as UTC with
    the tzinfo **stripped** and a space separator — no ``T``, no ``+00:00``.
    Getting this wrong makes rows unreadable by Django and breaks the admin's
    ``date_hierarchy``. PostgreSQL keeps the aware value; the driver handles it.
    """
    if value.tzinfo is None:
        value = value.replace(tzinfo=timezone.utc)
    d = normalize_dialect(dialect)
    if d == "postgresql":
        return value.astimezone(timezone.utc)
    naive = value.astimezone(timezone.utc).replace(tzinfo=None)
    if d == "mysql":
        return naive
    return naive.isoformat(sep=" ")
