"""The table shape, defined exactly once.

``COLUMNS`` is the single source of column order for every backend's INSERT and
for the DDL emitted by :func:`ddl_for`. The DDL is hand-written to match what
Django's own migration produces for
``eventlog_pro.contrib.django.models.EventLog``, so a table created by the core
backends can be adopted by ``migrate --fake-initial`` and both modes can read
each other's rows. ``tests/test_schema_parity.py`` enforces that promise.
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from typing import TYPE_CHECKING, Any, Final

from .exceptions import BackendError, ConfigurationError

if TYPE_CHECKING:  # pragma: no cover
    from .criteria import Criteria

__all__ = [
    "COLUMNS",
    "CHAR_COLUMNS",
    "SELECT_COLUMNS",
    "MAX_CHARFIELD_LENGTH",
    "DEFAULT_TABLE",
    "DIALECTS",
    "INDEXES",
    "validate_table_name",
    "normalize_dialect",
    "quote_identifier",
    "placeholder",
    "ddl_for",
    "create_table_sql",
    "index_statements",
    "insert_sql",
    "select_sql",
    "select_ids_sql",
    "delete_sql",
    "delete_by_ids_sql",
    "where_clause",
    "order_clause",
    "like_pattern",
    "to_db_datetime",
    "from_db_datetime",
    "from_db_data",
]

#: Column order, matching the declaration order of the Django model.
COLUMNS: Final[tuple[str, ...]] = (
    "created_at",
    "created_by",
    "app",
    "category",
    "sub_category",
    "event_code",
    "event_type",
    "entity_app",
    "entity_model",
    "entity_id",
    "remarks",
    "data",
)

#: Column order for reads: the stored columns, with ``id`` in front.
SELECT_COLUMNS: Final[tuple[str, ...]] = ("id", *COLUMNS)

#: The ``varchar(100)`` columns. Values are truncated to fit, never rejected.
CHAR_COLUMNS: Final[tuple[str, ...]] = (
    "created_by",
    "app",
    "category",
    "sub_category",
    "event_code",
    "event_type",
    "entity_app",
    "entity_model",
    "entity_id",
)

MAX_CHARFIELD_LENGTH: Final[int] = 100

DEFAULT_TABLE: Final[str] = "eventlog_eventlog"

DIALECTS: Final[tuple[str, ...]] = ("sqlite", "postgresql", "mysql")

_DIALECT_ALIASES: Final[dict[str, str]] = {
    "sqlite": "sqlite",
    "sqlite3": "sqlite",
    "postgres": "postgresql",
    "postgresql": "postgresql",
    "psycopg": "postgresql",
    "mysql": "mysql",
    "mariadb": "mysql",
}

#: ``(name suffix, indexed expression)`` — the three indexes the source app
#: lacks. Shipped in the Django app as ``0002_add_indexes`` so an existing
#: install can ``--fake-initial`` 0001 and really apply 0002.
INDEXES: Final[tuple[tuple[str, tuple[str, ...]], ...]] = (
    ("created", ("created_at DESC",)),
    ("app_cat", ("app", "category", "event_code")),
    ("entity", ("entity_app", "entity_model", "entity_id")),
)

#: Django refuses index names longer than this (``models.E034``), for Oracle's
#: sake. The core DDL and the model must agree, so both go through
#: :func:`index_name` and both stay inside the limit.
MAX_INDEX_NAME_LENGTH: Final[int] = 30

# Per-dialect column types. Kept verbatim-comparable to Django's schema editor
# output; see the parity test before touching anything here.
_TYPES: Final[dict[str, dict[str, str]]] = {
    "sqlite": {
        "id": "integer NOT NULL PRIMARY KEY AUTOINCREMENT",
        "created_at": "datetime NOT NULL",
        "char": f"varchar({MAX_CHARFIELD_LENGTH}) NOT NULL",
        "remarks": "text NOT NULL",
        # Django's SQLite JSONField carries this CHECK constraint.
        "data": 'text NOT NULL CHECK ((JSON_VALID("data") OR "data" IS NULL))',
    },
    "postgresql": {
        # Django >= 4.1 emits an identity column, not bigserial.
        "id": "bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "created_at": "timestamp with time zone NOT NULL",
        "char": f"varchar({MAX_CHARFIELD_LENGTH}) NOT NULL",
        "remarks": "text NOT NULL",
        "data": "jsonb NOT NULL",
    },
    "mysql": {
        "id": "bigint NOT NULL AUTO_INCREMENT PRIMARY KEY",
        "created_at": "datetime(6) NOT NULL",
        "char": f"varchar({MAX_CHARFIELD_LENGTH}) NOT NULL",
        "remarks": "longtext NOT NULL",
        "data": "json NOT NULL",
    },
}

_TABLE_NAME_ALLOWED = frozenset("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_")


def normalize_dialect(dialect: str) -> str:
    """Map a DSN scheme or dialect alias onto one of :data:`DIALECTS`."""
    try:
        return _DIALECT_ALIASES[dialect.lower()]
    except KeyError:
        raise ConfigurationError(
            f"Unknown SQL dialect {dialect!r}. Known: {', '.join(DIALECTS)}."
        ) from None


def validate_table_name(table: str) -> str:
    """Validate the one user string that reaches SQL unparameterised.

    A whitelist, not an escape function: ``^[A-Za-z_][A-Za-z0-9_]*$``, at most
    64 characters (the tightest limit among the supported databases).
    """
    if not table:
        raise ConfigurationError("Table name must not be empty.")
    if len(table) > 64:
        raise ConfigurationError(f"Table name {table!r} is longer than 64 characters.")
    if table[0].isdigit() or not set(table) <= _TABLE_NAME_ALLOWED:
        raise ConfigurationError(
            f"Invalid table name {table!r}. Table names must match ^[A-Za-z_][A-Za-z0-9_]*$."
        )
    return table


def quote_identifier(name: str, dialect: str) -> str:
    """Quote an already-validated identifier for *dialect*."""
    return f"`{name}`" if normalize_dialect(dialect) == "mysql" else f'"{name}"'


def placeholder(dialect: str, column: str = "") -> str:
    """The parameter placeholder for *column* in *dialect*."""
    d = normalize_dialect(dialect)
    if d == "sqlite":
        return "?"
    if d == "postgresql" and column == "data":
        # json.dumps on the Python side, cast in SQL — never psycopg's Jsonb.
        return "%s::jsonb"
    return "%s"


def create_table_sql(dialect: str, table: str) -> str:
    """``CREATE TABLE IF NOT EXISTS`` for *table* in *dialect*."""
    d = normalize_dialect(dialect)
    table = validate_table_name(table)
    types = _TYPES[d]
    q = quote_identifier

    defs = [f"{q('id', d)} {types['id']}"]
    for column in COLUMNS:
        if column == "created_at":
            column_type = types["created_at"]
        elif column in CHAR_COLUMNS:
            column_type = types["char"]
        elif column == "remarks":
            column_type = types["remarks"]
        else:
            column_type = types["data"]
        defs.append(f"{q(column, d)} {column_type}")

    body = ",\n    ".join(defs)
    suffix = " ENGINE=InnoDB DEFAULT CHARSET=utf8mb4" if d == "mysql" else ""
    return f"CREATE TABLE IF NOT EXISTS {q(table, d)} (\n    {body}\n){suffix}"


def index_name(table: str, suffix: str) -> str:
    """Deterministic index name, at most :data:`MAX_INDEX_NAME_LENGTH` characters.

    Readable for the default table (``eventlog_eventlog_created``); for a long
    custom table name it falls back to a short prefix plus a digest of the
    table, which stays deterministic and collision-free.
    """
    name = f"{table}_{suffix}"
    if len(name) <= MAX_INDEX_NAME_LENGTH:
        return name
    digest = hashlib.md5(name.encode("utf-8"), usedforsecurity=False).hexdigest()[:8]
    return f"el_{suffix}_{digest}"[:MAX_INDEX_NAME_LENGTH]


def index_statements(dialect: str, table: str) -> tuple[str, ...]:
    """The three ``CREATE INDEX`` statements.

    MySQL has no ``CREATE INDEX IF NOT EXISTS``; its backend swallows the
    duplicate-key-name error instead.
    """
    d = normalize_dialect(dialect)
    table = validate_table_name(table)
    q = quote_identifier
    if_not_exists = "" if d == "mysql" else "IF NOT EXISTS "

    statements = []
    for suffix, columns in INDEXES:
        cols = ", ".join(
            f"{q(c.split(' ')[0], d)} {c.split(' ', 1)[1]}" if " " in c else q(c, d)
            for c in columns
        )
        statements.append(
            f"CREATE INDEX {if_not_exists}{q(index_name(table, suffix), d)} "
            f"ON {q(table, d)} ({cols})"
        )
    return tuple(statements)


def ddl_for(dialect: str, table: str = DEFAULT_TABLE) -> tuple[str, ...]:
    """Every statement needed to materialise the event table in *dialect*."""
    return (create_table_sql(dialect, table), *index_statements(dialect, table))


def insert_sql(dialect: str, table: str = DEFAULT_TABLE) -> str:
    """``INSERT`` covering all of :data:`COLUMNS`, in order."""
    d = normalize_dialect(dialect)
    table = validate_table_name(table)
    q = quote_identifier
    columns = ", ".join(q(c, d) for c in COLUMNS)
    values = ", ".join(placeholder(d, c) for c in COLUMNS)
    sql = f"INSERT INTO {q(table, d)} ({columns}) VALUES ({values})"
    if d == "postgresql":
        sql += f" RETURNING {q('id', d)}, {q('created_at', d)}"
    return sql


def like_pattern(value: str) -> str:
    """Wrap *value* in ``%`` wildcards, escaping the ones it contains itself.

    Backslash first, or the escapes introduced for ``%`` and ``_`` would
    themselves be escaped. Backslash is the escape character on every dialect
    here — see :func:`_contains_clause` for how each one is told so.
    """
    escaped = value.replace("\\", "\\\\").replace("%", "\\%").replace("_", "\\_")
    return f"%{escaped}%"


def _contains_clause(column: str, dialect: str) -> str:
    """``LIKE`` against *column* rendered as text.

    PostgreSQL's ``jsonb`` and MySQL's ``json`` are not text and will not
    compare to one; SQLite's is already ``text``. The cast is what makes one
    substring filter mean roughly the same thing on all three.

    **MySQL gets no ``ESCAPE`` clause.** Backslash is already its default
    ``LIKE`` escape character, and spelling it out is a trap: MySQL treats
    backslash as an escape *inside string literals* too, so the literal
    ``'\\'`` reads as an escaped quote and the statement dies with a 1064
    syntax error. Writing ``'\\\\'`` instead would fix that but break under
    ``NO_BACKSLASH_ESCAPES``, where it means two characters and ``ESCAPE``
    demands one. Omitting the clause is correct in both modes.
    """
    d = normalize_dialect(dialect)
    q = quote_identifier
    if d == "postgresql":
        target = f"{q(column, d)}::text"
    elif d == "mysql" and column == "data":
        target = f"CAST({q(column, d)} AS CHAR)"
    else:
        target = q(column, d)
    clause = f"{target} LIKE {placeholder(d)}"
    return clause if d == "mysql" else f"{clause} ESCAPE '\\'"


def where_clause(dialect: str, criteria: Criteria) -> tuple[str, tuple[Any, ...]]:
    """The ``WHERE`` clause for *criteria*, plus the values to bind.

    Returns ``("", ())`` when nothing is filtered. Every value is bound;
    the only strings interpolated are column names, all of which came from
    :data:`SELECT_COLUMNS` by way of ``criteria``.
    """
    d = normalize_dialect(dialect)
    q = quote_identifier
    parts: list[str] = []
    params: list[Any] = []

    for column, value in criteria.equals:
        parts.append(f"{q(column, d)} = {placeholder(d)}")
        params.append(value)

    for column, needle in criteria.contains:
        parts.append(_contains_clause(column, d))
        params.append(like_pattern(needle))

    if criteria.created_from is not None:
        parts.append(f"{q('created_at', d)} >= {placeholder(d)}")
        params.append(to_db_datetime(criteria.created_from, d))

    if criteria.created_to is not None:
        parts.append(f"{q('created_at', d)} {criteria.created_to_op} {placeholder(d)}")
        params.append(to_db_datetime(criteria.created_to, d))

    if not parts:
        return ("", ())
    return (" WHERE " + " AND ".join(parts), tuple(params))


def order_clause(dialect: str, order_by: tuple[tuple[str, str], ...]) -> str:
    """The ``ORDER BY`` clause, or ``""`` when there is nothing to order by."""
    if not order_by:
        return ""
    d = normalize_dialect(dialect)
    q = quote_identifier
    terms = ", ".join(f"{q(name, d)} {direction}" for name, direction in order_by)
    return f" ORDER BY {terms}"


def _limit_clause(limit: int | None) -> str:
    """``LIMIT n``, with *n* interpolated rather than bound.

    Binding it would be portable too, but the three drivers disagree about
    placeholders in ``LIMIT``, and the value is an ``int`` that
    ``build_criteria`` has already validated — there is no string to inject.
    """
    return "" if limit is None else f" LIMIT {int(limit)}"


def select_sql(
    dialect: str, table: str = DEFAULT_TABLE, criteria: Criteria | None = None
) -> tuple[str, tuple[Any, ...]]:
    """``SELECT`` every column of every matching row."""
    d = normalize_dialect(dialect)
    table = validate_table_name(table)
    q = quote_identifier
    columns = ", ".join(q(c, d) for c in SELECT_COLUMNS)
    if criteria is None:
        return (f"SELECT {columns} FROM {q(table, d)}", ())
    where, params = where_clause(d, criteria)
    sql = (
        f"SELECT {columns} FROM {q(table, d)}"
        f"{where}{order_clause(d, criteria.order_by)}{_limit_clause(criteria.limit)}"
    )
    return (sql, params)


def select_ids_sql(dialect: str, table: str, criteria: Criteria) -> tuple[str, tuple[Any, ...]]:
    """``SELECT id`` for a limited delete — step one of the two-statement form."""
    d = normalize_dialect(dialect)
    table = validate_table_name(table)
    q = quote_identifier
    where, params = where_clause(d, criteria)
    sql = (
        f"SELECT {q('id', d)} FROM {q(table, d)}"
        f"{where}{order_clause(d, criteria.order_by)}{_limit_clause(criteria.limit)}"
    )
    return (sql, params)


def delete_sql(dialect: str, table: str, criteria: Criteria) -> tuple[str, tuple[Any, ...]]:
    """``DELETE`` every matching row.

    No ``LIMIT``: PostgreSQL has no ``DELETE ... LIMIT`` at all and SQLite is
    normally compiled without it, so a limited delete goes through
    :func:`select_ids_sql` and :func:`delete_by_ids_sql` instead.
    """
    d = normalize_dialect(dialect)
    table = validate_table_name(table)
    where, params = where_clause(d, criteria)
    return (f"DELETE FROM {quote_identifier(table, d)}{where}", params)


def delete_by_ids_sql(
    dialect: str, table: str, ids: tuple[Any, ...]
) -> tuple[str, tuple[Any, ...]]:
    """``DELETE ... WHERE id IN (…)`` — step two of the two-statement form."""
    d = normalize_dialect(dialect)
    table = validate_table_name(table)
    q = quote_identifier
    placeholders = ", ".join(placeholder(d) for _ in ids)
    sql = f"DELETE FROM {q(table, d)} WHERE {q('id', d)} IN ({placeholders})"
    return (sql, tuple(ids))


def to_db_datetime(value: datetime, dialect: str) -> datetime | str:
    """Render *value* the way Django's converters expect to read it back.

    With ``USE_TZ=True`` Django stores SQLite and MySQL datetimes as UTC with
    the tzinfo **stripped** and a space separator — no ``T``, no ``+00:00``.
    Getting this wrong makes rows unreadable by Django and breaks the admin's
    ``date_hierarchy``. PostgreSQL keeps the aware value; the driver handles it.
    """
    if value.tzinfo is None:
        value = value.replace(tzinfo=timezone.utc)
    d = normalize_dialect(dialect)
    if d == "postgresql":
        return value.astimezone(timezone.utc)
    naive = value.astimezone(timezone.utc).replace(tzinfo=None)
    if d == "mysql":
        return naive
    return naive.isoformat(sep=" ")


def from_db_datetime(value: Any, dialect: str) -> datetime:
    """Read back what :func:`to_db_datetime` wrote, always tz-aware UTC.

    Deliberately more forgiving than that function is strict: rows in an
    adopted table may have been written by Django rather than by this package,
    so a ``T`` separator, a missing microsecond component and a trailing ``Z``
    all have to parse. Anything already aware is just converted.
    """
    if isinstance(value, datetime):
        if value.tzinfo is None:
            return value.replace(tzinfo=timezone.utc)
        return value.astimezone(timezone.utc)
    if isinstance(value, str):
        text = value.strip()
        if text.endswith(("Z", "z")):
            # 3.10's fromisoformat does not accept the military-time suffix.
            text = f"{text[:-1]}+00:00"
        try:
            parsed = datetime.fromisoformat(text)
        except ValueError as exc:
            raise BackendError(
                f"Could not read created_at {value!r} from the {dialect} store."
            ) from exc
        return parsed.replace(tzinfo=timezone.utc) if parsed.tzinfo is None else parsed
    raise BackendError(
        f"Could not read created_at {value!r} ({type(value).__name__}) from the {dialect} store."
    )


def from_db_data(value: Any) -> Any:
    """Read back the ``data`` column, which drivers hand over inconsistently.

    ``jsonb``/``json`` columns arrive already decoded; SQLite's ``text`` one
    arrives as a string. A string that is not valid JSON is returned as-is
    rather than raised on — a row nobody can read is worse than a surprising
    one, and this is a log.
    """
    if value is None:
        return {}
    if isinstance(value, (str, bytes, bytearray)):
        try:
            return json.loads(value)
        except (ValueError, UnicodeDecodeError):
            return value if isinstance(value, str) else value.decode("utf-8", "replace")
    return value
