"""Schema: column order, DDL per dialect, table-name validation, datetimes."""

from __future__ import annotations

from datetime import date, datetime, timedelta, timezone

import pytest

from eventlog_pro import BackendError, ConfigurationError
from eventlog_pro.schema import (
    CHAR_COLUMNS,
    COLUMNS,
    MAX_INDEX_NAME_LENGTH,
    create_table_sql,
    ddl_for,
    delete_by_ids_sql,
    delete_sql,
    from_db_data,
    from_db_datetime,
    index_name,
    index_statements,
    insert_sql,
    normalize_dialect,
    placeholder,
    select_ids_sql,
    select_sql,
    to_db_datetime,
    validate_table_name,
)


def test_column_order_matches_the_django_model_declaration():
    assert COLUMNS == (
        "created_at",
        "created_by",
        "app",
        "category",
        "sub_category",
        "event_code",
        "event_type",
        "entity_app",
        "entity_model",
        "entity_id",
        "remarks",
        "data",
    )
    assert set(CHAR_COLUMNS) < set(COLUMNS)
    assert "created_at" not in CHAR_COLUMNS and "data" not in CHAR_COLUMNS


@pytest.mark.parametrize(
    "alias,expected",
    [
        ("sqlite", "sqlite"),
        ("sqlite3", "sqlite"),
        ("postgres", "postgresql"),
        ("POSTGRESQL", "postgresql"),
        ("mariadb", "mysql"),
        ("mysql", "mysql"),
    ],
)
def test_dialect_aliases(alias, expected):
    assert normalize_dialect(alias) == expected


def test_unknown_dialect_is_a_configuration_error():
    with pytest.raises(ConfigurationError, match="Unknown SQL dialect"):
        normalize_dialect("oracle")


@pytest.mark.parametrize("name", ["", "1abc", "drop table x;--", "a-b", "a b", "x" * 65])
def test_bad_table_names_are_rejected(name):
    with pytest.raises(ConfigurationError):
        validate_table_name(name)


@pytest.mark.parametrize("name", ["eventlog_eventlog", "_x", "AuditEvents2"])
def test_good_table_names_pass(name):
    assert validate_table_name(name) == name


def test_sqlite_ddl_matches_what_django_emits():
    sql = create_table_sql("sqlite", "eventlog_eventlog")
    assert '"id" integer NOT NULL PRIMARY KEY AUTOINCREMENT' in sql
    assert '"created_at" datetime NOT NULL' in sql
    assert '"app" varchar(100) NOT NULL' in sql
    assert '"remarks" text NOT NULL' in sql
    assert '"data" text NOT NULL CHECK ((JSON_VALID("data") OR "data" IS NULL))' in sql


def test_postgres_ddl_uses_identity_and_jsonb():
    sql = create_table_sql("postgresql", "eventlog_eventlog")
    assert '"id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' in sql
    assert "bigserial" not in sql
    assert '"created_at" timestamp with time zone NOT NULL' in sql
    assert '"data" jsonb NOT NULL' in sql


def test_mysql_ddl_uses_utf8mb4_and_microseconds():
    sql = create_table_sql("mysql", "eventlog_eventlog")
    assert "`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY" in sql
    assert "`created_at` datetime(6) NOT NULL" in sql
    assert "`remarks` longtext NOT NULL" in sql
    assert "`data` json NOT NULL" in sql
    assert sql.endswith("ENGINE=InnoDB DEFAULT CHARSET=utf8mb4")


def test_ddl_is_create_table_plus_three_indexes():
    statements = ddl_for("sqlite", "eventlog_eventlog")
    assert len(statements) == 4
    assert statements[0].startswith("CREATE TABLE IF NOT EXISTS")
    assert all(s.startswith("CREATE INDEX") for s in statements[1:])


def test_indexes_cover_the_three_query_shapes():
    statements = index_statements("sqlite", "eventlog_eventlog")
    assert '("created_at" DESC)' in statements[0]
    assert '("app", "category", "event_code")' in statements[1]
    assert '("entity_app", "entity_model", "entity_id")' in statements[2]


def test_mysql_has_no_if_not_exists_on_indexes():
    # MySQL does not support it; the backend swallows errno 1061 instead.
    assert all("IF NOT EXISTS" not in s for s in index_statements("mysql", "t"))
    assert all("IF NOT EXISTS" in s for s in index_statements("postgresql", "t"))


def test_index_names_stay_within_djangos_limit():
    for suffix in ("created", "app_cat", "entity"):
        assert len(index_name("eventlog_eventlog", suffix)) <= MAX_INDEX_NAME_LENGTH
        long_name = index_name("a_very_long_custom_table_name_indeed", suffix)
        assert len(long_name) <= MAX_INDEX_NAME_LENGTH
    # Deterministic, and distinct per table.
    assert index_name("t_one" * 8, "entity") != index_name("t_two" * 8, "entity")
    assert index_name("x" * 40, "entity") == index_name("x" * 40, "entity")


def test_insert_covers_every_column_in_order():
    sql = insert_sql("sqlite", "eventlog_eventlog")
    columns = sql.split("(")[1].split(")")[0]
    assert columns == ", ".join(f'"{c}"' for c in COLUMNS)
    assert sql.count("?") == len(COLUMNS)


def test_postgres_insert_casts_json_and_returns_the_row():
    sql = insert_sql("postgresql", "eventlog_eventlog")
    assert "%s::jsonb" in sql
    assert sql.endswith('RETURNING "id", "created_at"')


def test_placeholders_per_dialect():
    assert placeholder("sqlite", "data") == "?"
    assert placeholder("postgresql", "data") == "%s::jsonb"
    assert placeholder("postgresql", "app") == "%s"
    assert placeholder("mysql", "data") == "%s"


def test_table_name_is_validated_before_reaching_sql():
    with pytest.raises(ConfigurationError):
        insert_sql("sqlite", 'x"; DROP TABLE users; --')


def test_created_at_is_stored_the_way_django_reads_it():
    """Space separator, no offset, UTC — an ISO 'T' breaks Django's converter."""
    aware = datetime(2026, 8, 12, 23, 30, 0, 123456, tzinfo=timezone(timedelta(hours=-4)))
    rendered = to_db_datetime(aware, "sqlite")
    assert rendered == "2026-08-13 03:30:00.123456"
    assert "T" not in rendered and "+" not in rendered


def test_mysql_gets_a_naive_utc_datetime_object():
    aware = datetime(2026, 8, 12, 10, 0, tzinfo=timezone.utc)
    assert to_db_datetime(aware, "mysql") == datetime(2026, 8, 12, 10, 0)
    assert to_db_datetime(aware, "mysql").tzinfo is None


def test_postgres_keeps_the_aware_value():
    aware = datetime(2026, 8, 12, 10, 0, tzinfo=timezone.utc)
    assert to_db_datetime(aware, "postgresql") == aware


def test_naive_input_is_treated_as_utc():
    assert to_db_datetime(datetime(2026, 8, 12, 10, 0), "sqlite") == "2026-08-12 10:00:00"


def test_sqlite_timestamps_are_fixed_width_so_range_filters_can_compare_them():
    """The range filters compare `created_at` as text on SQLite.

    That only works because every stored value is zero-padded to the same
    width, which makes lexicographic order agree with chronological order. If
    this ever changes, `from_created_at` / `to_created_at` break silently.
    """
    early = to_db_datetime(datetime(2026, 8, 9, 9, 5, 1, 7, tzinfo=timezone.utc), "sqlite")
    late = to_db_datetime(datetime(2026, 8, 10, 10, 5, 1, 7, tzinfo=timezone.utc), "sqlite")
    assert early == "2026-08-09 09:05:01.000007"
    assert len(early) == len(late) and early < late


@pytest.mark.parametrize(
    ("stored", "dialect"),
    [
        ("2026-08-12 10:00:00.123456", "sqlite"),
        ("2026-08-12T10:00:00.123456", "sqlite"),  # written by something else
        ("2026-08-12 10:00:00.123456+00:00", "sqlite"),
        ("2026-08-12T10:00:00.123456Z", "jsonl"),
        (datetime(2026, 8, 12, 10, 0, 0, 123456), "mysql"),
        (datetime(2026, 8, 12, 10, 0, 0, 123456, tzinfo=timezone.utc), "postgresql"),
    ],
)
def test_created_at_reads_back_as_aware_utc(stored, dialect):
    parsed = from_db_datetime(stored, dialect)
    assert parsed == datetime(2026, 8, 12, 10, 0, 0, 123456, tzinfo=timezone.utc)
    assert parsed.tzinfo is not None


def test_a_missing_microsecond_component_still_parses():
    # Django writes second-resolution timestamps for some backends.
    assert from_db_datetime("2026-08-12 10:00:00", "sqlite") == datetime(
        2026, 8, 12, 10, 0, tzinfo=timezone.utc
    )


def test_an_unreadable_timestamp_is_a_backend_error():
    with pytest.raises(BackendError):
        from_db_datetime("not a date", "sqlite")


def test_data_reads_back_as_a_dict_whatever_the_driver_hands_over():
    assert from_db_data('{"n": 1}') == {"n": 1}
    assert from_db_data(b'{"n": 1}') == {"n": 1}
    assert from_db_data({"n": 1}) == {"n": 1}
    assert from_db_data(None) == {}
    assert from_db_data("not json") == "not json"  # a log row is never unreadable


# ---------------------------------------------------------------- query SQL


def _criteria(**kwargs):
    from eventlog_pro.criteria import build_criteria

    return build_criteria(**kwargs)


def test_select_sql_binds_every_value_and_quotes_every_name():
    sql, params = select_sql("sqlite", "t", _criteria(app="api", limit=5))
    assert sql == (
        'SELECT "id", "created_at", "created_by", "app", "category", "sub_category", '
        '"event_code", "event_type", "entity_app", "entity_model", "entity_id", '
        '"remarks", "data" FROM "t" WHERE "app" = ? '
        'ORDER BY "created_at" DESC, "id" DESC LIMIT 5'
    )
    assert params == ("api",)


def test_placeholders_follow_the_dialect():
    sql, _ = select_sql("postgresql", "t", _criteria(app="api"))
    assert '"app" = %s' in sql
    sql, _ = select_sql("mysql", "t", _criteria(app="api"))
    assert "`app` = %s" in sql


def test_a_date_range_becomes_gte_and_lt():
    sql, params = select_sql("sqlite", "t", _criteria(to_created_at=date(2026, 8, 14), limit=None))
    assert '"created_at" < ?' in sql
    assert params == ("2026-08-15 00:00:00",)


def test_a_datetime_upper_bound_becomes_lte():
    moment = datetime(2026, 8, 14, 12, 0, tzinfo=timezone.utc)
    sql, _ = select_sql("sqlite", "t", _criteria(to_created_at=moment, limit=None))
    assert '"created_at" <= ?' in sql


def test_the_data_filter_casts_to_text_per_dialect():
    criteria = _criteria(data="INV")
    assert '"data" LIKE ?' in select_sql("sqlite", "t", criteria)[0]
    assert '"data"::text LIKE %s' in select_sql("postgresql", "t", criteria)[0]
    assert "CAST(`data` AS CHAR) LIKE %s" in select_sql("mysql", "t", criteria)[0]


def test_the_data_filter_escapes_like_wildcards():
    _sql, params = select_sql("sqlite", "t", _criteria(data="50%_off"))
    assert params == (r"%50\%\_off%",)


def test_mysql_gets_no_escape_clause():
    """MySQL's default LIKE escape is already backslash, and saying so breaks it.

    MySQL treats backslash as an escape character inside string literals too,
    so `ESCAPE '\\'` reads as an escaped quote and the statement dies with a
    1064 syntax error. `ESCAPE '\\\\'` would fix that and then break under
    NO_BACKSLASH_ESCAPES. Omitting the clause is right in both modes.
    """
    criteria = _criteria(data="x")
    assert "ESCAPE" not in select_sql("mysql", "t", criteria)[0]
    assert "ESCAPE '\\'" in select_sql("sqlite", "t", criteria)[0]
    assert "ESCAPE '\\'" in select_sql("postgresql", "t", criteria)[0]


def test_delete_sql_has_no_limit_clause():
    # PostgreSQL has no DELETE ... LIMIT and SQLite is normally built without
    # it, so a limited delete goes through select_ids_sql instead.
    sql, params = delete_sql("sqlite", "t", _criteria(app="api", for_delete=True, limit=10))
    assert sql == 'DELETE FROM "t" WHERE "app" = ?'
    assert "LIMIT" not in sql
    assert params == ("api",)


def test_select_ids_sql_orders_oldest_first_for_a_limited_delete():
    sql, _ = select_ids_sql("sqlite", "t", _criteria(app="api", for_delete=True, limit=10))
    assert sql == (
        'SELECT "id" FROM "t" WHERE "app" = ? ORDER BY "created_at" ASC, "id" ASC LIMIT 10'
    )


def test_delete_by_ids_sql_binds_one_placeholder_per_id():
    sql, params = delete_by_ids_sql("sqlite", "t", (1, 2, 3))
    assert sql == 'DELETE FROM "t" WHERE "id" IN (?, ?, ?)'
    assert params == (1, 2, 3)


def test_an_unfiltered_select_has_no_where_clause():
    sql, params = select_sql("sqlite", "t", _criteria(limit=None))
    assert "WHERE" not in sql
    assert params == ()


def test_the_table_name_is_still_validated_on_the_read_path():
    with pytest.raises(ConfigurationError):
        select_sql("sqlite", 'x"; DROP TABLE users; --', _criteria())
