"""Schema: column order, DDL per dialect, table-name validation, datetimes."""

from __future__ import annotations

from datetime import datetime, timedelta, timezone

import pytest

from eventlog_pro import ConfigurationError
from eventlog_pro.schema import (
    CHAR_COLUMNS,
    COLUMNS,
    MAX_INDEX_NAME_LENGTH,
    create_table_sql,
    ddl_for,
    index_name,
    index_statements,
    insert_sql,
    normalize_dialect,
    placeholder,
    to_db_datetime,
    validate_table_name,
)


def test_column_order_matches_the_django_model_declaration():
    assert COLUMNS == (
        "created_at",
        "created_by",
        "app",
        "category",
        "sub_category",
        "event_code",
        "event_type",
        "entity_app",
        "entity_model",
        "entity_id",
        "remarks",
        "data",
    )
    assert set(CHAR_COLUMNS) < set(COLUMNS)
    assert "created_at" not in CHAR_COLUMNS and "data" not in CHAR_COLUMNS


@pytest.mark.parametrize(
    "alias,expected",
    [
        ("sqlite", "sqlite"),
        ("sqlite3", "sqlite"),
        ("postgres", "postgresql"),
        ("POSTGRESQL", "postgresql"),
        ("mariadb", "mysql"),
        ("mysql", "mysql"),
    ],
)
def test_dialect_aliases(alias, expected):
    assert normalize_dialect(alias) == expected


def test_unknown_dialect_is_a_configuration_error():
    with pytest.raises(ConfigurationError, match="Unknown SQL dialect"):
        normalize_dialect("oracle")


@pytest.mark.parametrize("name", ["", "1abc", "drop table x;--", "a-b", "a b", "x" * 65])
def test_bad_table_names_are_rejected(name):
    with pytest.raises(ConfigurationError):
        validate_table_name(name)


@pytest.mark.parametrize("name", ["eventlog_eventlog", "_x", "AuditEvents2"])
def test_good_table_names_pass(name):
    assert validate_table_name(name) == name


def test_sqlite_ddl_matches_what_django_emits():
    sql = create_table_sql("sqlite", "eventlog_eventlog")
    assert '"id" integer NOT NULL PRIMARY KEY AUTOINCREMENT' in sql
    assert '"created_at" datetime NOT NULL' in sql
    assert '"app" varchar(100) NOT NULL' in sql
    assert '"remarks" text NOT NULL' in sql
    assert '"data" text NOT NULL CHECK ((JSON_VALID("data") OR "data" IS NULL))' in sql


def test_postgres_ddl_uses_identity_and_jsonb():
    sql = create_table_sql("postgresql", "eventlog_eventlog")
    assert '"id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' in sql
    assert "bigserial" not in sql
    assert '"created_at" timestamp with time zone NOT NULL' in sql
    assert '"data" jsonb NOT NULL' in sql


def test_mysql_ddl_uses_utf8mb4_and_microseconds():
    sql = create_table_sql("mysql", "eventlog_eventlog")
    assert "`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY" in sql
    assert "`created_at` datetime(6) NOT NULL" in sql
    assert "`remarks` longtext NOT NULL" in sql
    assert "`data` json NOT NULL" in sql
    assert sql.endswith("ENGINE=InnoDB DEFAULT CHARSET=utf8mb4")


def test_ddl_is_create_table_plus_three_indexes():
    statements = ddl_for("sqlite", "eventlog_eventlog")
    assert len(statements) == 4
    assert statements[0].startswith("CREATE TABLE IF NOT EXISTS")
    assert all(s.startswith("CREATE INDEX") for s in statements[1:])


def test_indexes_cover_the_three_query_shapes():
    statements = index_statements("sqlite", "eventlog_eventlog")
    assert '("created_at" DESC)' in statements[0]
    assert '("app", "category", "event_code")' in statements[1]
    assert '("entity_app", "entity_model", "entity_id")' in statements[2]


def test_mysql_has_no_if_not_exists_on_indexes():
    # MySQL does not support it; the backend swallows errno 1061 instead.
    assert all("IF NOT EXISTS" not in s for s in index_statements("mysql", "t"))
    assert all("IF NOT EXISTS" in s for s in index_statements("postgresql", "t"))


def test_index_names_stay_within_djangos_limit():
    for suffix in ("created", "app_cat", "entity"):
        assert len(index_name("eventlog_eventlog", suffix)) <= MAX_INDEX_NAME_LENGTH
        long_name = index_name("a_very_long_custom_table_name_indeed", suffix)
        assert len(long_name) <= MAX_INDEX_NAME_LENGTH
    # Deterministic, and distinct per table.
    assert index_name("t_one" * 8, "entity") != index_name("t_two" * 8, "entity")
    assert index_name("x" * 40, "entity") == index_name("x" * 40, "entity")


def test_insert_covers_every_column_in_order():
    sql = insert_sql("sqlite", "eventlog_eventlog")
    columns = sql.split("(")[1].split(")")[0]
    assert columns == ", ".join(f'"{c}"' for c in COLUMNS)
    assert sql.count("?") == len(COLUMNS)


def test_postgres_insert_casts_json_and_returns_the_row():
    sql = insert_sql("postgresql", "eventlog_eventlog")
    assert "%s::jsonb" in sql
    assert sql.endswith('RETURNING "id", "created_at"')


def test_placeholders_per_dialect():
    assert placeholder("sqlite", "data") == "?"
    assert placeholder("postgresql", "data") == "%s::jsonb"
    assert placeholder("postgresql", "app") == "%s"
    assert placeholder("mysql", "data") == "%s"


def test_table_name_is_validated_before_reaching_sql():
    with pytest.raises(ConfigurationError):
        insert_sql("sqlite", 'x"; DROP TABLE users; --')


def test_created_at_is_stored_the_way_django_reads_it():
    """Space separator, no offset, UTC — an ISO 'T' breaks Django's converter."""
    aware = datetime(2026, 8, 12, 23, 30, 0, 123456, tzinfo=timezone(timedelta(hours=-4)))
    rendered = to_db_datetime(aware, "sqlite")
    assert rendered == "2026-08-13 03:30:00.123456"
    assert "T" not in rendered and "+" not in rendered


def test_mysql_gets_a_naive_utc_datetime_object():
    aware = datetime(2026, 8, 12, 10, 0, tzinfo=timezone.utc)
    assert to_db_datetime(aware, "mysql") == datetime(2026, 8, 12, 10, 0)
    assert to_db_datetime(aware, "mysql").tzinfo is None


def test_postgres_keeps_the_aware_value():
    aware = datetime(2026, 8, 12, 10, 0, tzinfo=timezone.utc)
    assert to_db_datetime(aware, "postgresql") == aware


def test_naive_input_is_treated_as_utc():
    assert to_db_datetime(datetime(2026, 8, 12, 10, 0), "sqlite") == "2026-08-12 10:00:00"
